apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-backup-user
  namespace: openshift-backup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-backup-view-all
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["*"]
  verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openshift-backup-user
subjects:
  - kind: ServiceAccount
    name: openshift-backup-user
    namespace: openshift-backup
roleRef:
  kind: ClusterRole
  name: openshift-backup-view-all
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:unprivileged
  namespace: openshift-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podsecuritypolicy:unprivileged
subjects:
  - kind: Group
    name: system:serviceaccounts:openshift-backup
    apiGroup: rbac.authorization.k8s.io
